version: "3"

networks:
  local:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  api:
    build: 
      context: ./emotion-chat-api
    working_dir: /emotion-chat-api
    container_name: emotion-chat-api
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229"
    expose:
      - "3000"
    volumes:
      - $PWD/emotion-chat-api:/emotion-chat-api
      - ./error.log:/usr/src/app/error.log
    networks:
      - local
    environment:
      - API_PORT=3000
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=azerty
      - POSTGRES_DB=emotion-chat-database
      - POSTGRES_PORT=5432
      - JWT_TOKEN_SECRET_KEY:DKFIRPKFMKLFHJ235456LDKFLD3K
    depends_on:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=azerty
      - POSTGRES_DB=emotion-chat-database
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - local

  webapp:
    build:
      context: ./emotion-chat-webapp
    working_dir: /emotion-chat-webapp
    container_name: emotion-chat-webapp
    restart: always
    ports:
      - "8080:8080"
      - "4200:4200"
    expose:
      - 4200
    volumes:
      - $PWD/emotion-chat-webapp:/emotion-chat-webapp
      - ./error.log:/usr/src/app/error.log
    networks:
      - local
